version: '3.8'

services:
  linkedin-api:
    build: .
    container_name: linkedin_generator_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always